edc.participant.id=transport-company-a
edc.hostname=consumer-identityhub

edc.iam.oauth2.issuer=http://localhost:8080/realms/logistics-dataspace
edc.iam.oauth2.jwks.url=http://host.docker.internal:8080/realms/logistics-dataspace/protocol/openid-connect/certs
edc.iam.did.web.use.https=false
EDC_IAM_DID_WEB_USE_HTTPS=false

edc.vault.hashicorp.url=http://host.docker.internal:8200
edc.vault.hashicorp.token=root

edc.datasource.default.url=jdbc:postgresql://consumer-identityhub-postgres:5432/identityhub
edc.datasource.default.user=identityhub
edc.datasource.default.password=identityhub
edc.sql.schema.autocreate=true

web.http.port=7080
web.http.path=/api

web.http.identity.port=7081
web.http.identity.path=/api/identity

web.http.credentials.port=7082
web.http.credentials.path=/api/credentials

web.http.did.port=7083
web.http.did.path=/

web.http.sts.port=7084
web.http.sts.path=/api/sts
